### ISSUE TITLE
A tic tac toe Game 

### ISSUE THREAD

**Issue by Nneoma12** [irm1005-itec1005-fall-2023/assignment-05-webweavers#1]
# Product Description

## High Level Overview

 We have decided to create a tic-tac-toe game that would be a blend of the different languages we learnt so far in the the course. 

## Problem Statement

 The problem we set aside to solve is boredom as well as being idle as this  weakens the brain but with the creation of this game it would spark critical thinking and gives people an activity to do which kills two emerging issues. 

## Moments of Charm

 we want to add a person dancing after each player takes a win which would make the game have an interactive feel with the winning player.

## Product Sketches

https://www.tldraw.com/r/Gr2oCRGANqANjCwHFrtlw?viewport=-140%2C-21%2C869%2C828&page=page%3Apage

**Comment by neilmispelaar** [comment]
Hey @irm1005-itec1005-fall-2023/webweavers 

Just a pro tip for the future - if you can - always include screenshots - makes it much easier for people reading / reviewing

<img width="1301" alt="Screenshot 2023-11-28 at 11 08 53 AM" src="https://github.com/irm1005-itec1005-fall-2023/assignment-05-webweavers/assets/9325038/d2960386-3155-4c31-83e9-9537e0c84bc9">

And, if you do include a link - try to make the link clickable as well. 

Great job all around - I love the idea and will provide more detailed feedback shortly.
